version: "3.7"
services:
  db:
    container_name: postgres-users-container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/data/db